Regular Exam - 18-Feb-2024/Task-2/URLShortener/Models/Home/IndexViewModel.cs
using URLShortener.Models.URLAddresses;

namespace URLShortener.Models.Home
{
    public class IndexViewModel
    {
        public int PageIndex { get;  set; }

        public int TotalPages { get;  set; }

        public bool HasPreviousPage => this.PageIndex > 1;

        public bool HasNextPage => this.PageIndex < this.TotalPages;

        public int URLsPerPage = 3;

        public int TotalShortURLsCount { get; set; }

        public int TotalURLVisitorsCount { get; set; }

        public int MyShortURLsCount { get; set; }

        public int MyTotalURLVisitorsCount { get; set; }

        public List<URLAddressViewModel>? URLAddresses { get; set; }
    }
}

Regular Exam - 18-Feb-2024/Task-2/URLShortener/Controllers/HomeController.cs
using System.Diagnostics;

using Microsoft.AspNetCore.Mvc;

using URLShortener.Infrastructure;
using URLShortener.Models;
using URLShortener.Models.Home;
using URLShortener.Models.URLAddresses;

using URLShortenerData.Data;
using URLShortenerData.Data.Entities;

namespace URLShortenerData.Controllers
{
    public class HomeController : Controller
    {
        private readonly URLShortenerDbContext data;

        public HomeController(URLShortenerDbContext data)
        {
            this.data = data;
        }

        public IActionResult Index(int? pageNumber)
        {
            IndexViewModel allIndexInfo = new IndexViewModel()
            {
                TotalShortURLsCount = this.data.URLAddresses.Count(),
                TotalURLVisitorsCount = this.GetAllUrlsVisitsCount(),
                URLAddresses = this.data.URLAddresses.Select(x => new URLAddressViewModel
                {
                    Id = x.Id,
                    OriginalUrl = x.OriginalUrl,
                    ShortUrl = x.ShortUrl,
                    DateCreated = x.DateCreated,
                    Visits = x.Visits
                }).OrderByDescending(x => x.DateCreated).Take(3).ToList()
            };

            if (this.User.Identity is not null && this.User.Identity.IsAuthenticated)
            {
                allIndexInfo.URLAddresses = this.data.URLAddresses
                    .Where(x => x.UserId == this.User.UserId())
                    .Select(x => new URLAddressViewModel
                    {
                        Id = x.Id,
                        OriginalUrl = x.OriginalUrl,
                        ShortUrl = x.ShortUrl,
                        DateCreated = x.DateCreated,
                        Visits = x.Visits
                    }).ToList();

                allIndexInfo.MyShortURLsCount = allIndexInfo.URLAddresses.Count();
                allIndexInfo.MyTotalURLVisitorsCount = this.GetMyUrlsVisistsCount(allIndexInfo);
            };

            allIndexInfo.PageIndex = pageNumber ?? 1;

            allIndexInfo.TotalPages = (int)Math.Ceiling((decimal)allIndexInfo.MyShortURLsCount / allIndexInfo.URLsPerPage);

            allIndexInfo.URLAddresses = allIndexInfo.URLAddresses
                .Skip((allIndexInfo.PageIndex - 1) * allIndexInfo.URLsPerPage)
                .Take(allIndexInfo.URLsPerPage)
                .ToList();

            return this.View(allIndexInfo);
        }

        private int GetMyUrlsVisistsCount(IndexViewModel allIndexInfo)
        {
            int myTotalVisits = 0;
            foreach (URLAddressViewModel urlAddress in allIndexInfo.URLAddresses!)
            {
                myTotalVisits += urlAddress.Visits;
            }

            return myTotalVisits;
        }

        private int GetAllUrlsVisitsCount()
        {
            int countAllVisits = 0;
            foreach (URLAddress address in this.data.URLAddresses)
            {
                countAllVisits += address.Visits;
            }

            return countAllVisits;
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error() => this.View(new ErrorViewModel
        { RequestId = Activity.Current?.Id ?? this.HttpContext.TraceIdentifier });
    }
}

Regular Exam - 18-Feb-2024/Task-2/URLShortener/Controllers/URLAddressController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

using URLShortener.Infrastructure;
using URLShortener.Models.URLAddresses;

using URLShortenerData.Data;
using URLShortenerData.Data.Entities;

namespace URLShortener.Controllers
{
    public class URLAddressController : Controller
    {
        private readonly URLShortenerDbContext context;

        public URLAddressController(URLShortenerDbContext data)
        {
            this.context = data;
        }

        public IActionResult All()
        {
            List<URLAddressViewModel> urlAddresses = this.context.URLAddresses
                .Select(x => new URLAddressViewModel
            {
                Id = x.Id,
                OriginalUrl = x.OriginalUrl,
                ShortUrl = x.ShortUrl,
                DateCreated = x.DateCreated,
                Visits = x.Visits
            }).ToList();

            return this.View(urlAddresses);
        }

        [Authorize]
        public IActionResult Add()
        {
            return this.View();
        }

        [Authorize]
        [HttpPost]
        public IActionResult Add(URLAddressFormModel model)
        {
            if (this.context.URLAddresses.Any(c => c.OriginalUrl == model.URL && c.UserId == this.User.UserId()))
            {
                this.ModelState.AddModelError(nameof(model.URL),
                    "You already have a short URL of that original URL!");
            }

            if (this.context.URLAddresses.Any(c => c.ShortUrl.Contains(model.ShortCode)))
            {
                this.ModelState.AddModelError(nameof(model.ShortCode),
                    $"A short code \"{model.ShortCode}\" already exists!");
            }

            if (!this.ModelState.IsValid)
            {
                return this.View(model);
            }

            URLAddress url = new URLAddress
            {
                OriginalUrl = model.URL,
                ShortUrl = "http://shorturl.nakov.repl.co/go/" + model.ShortCode,
                DateCreated = DateTime.UtcNow,
                UserId = this.User.UserId(),
                Visits = 0
            };

            this.context.URLAddresses.Add(url);
            this.context.SaveChanges();

            return this.RedirectToAction("Index", "Home");
        }

        [Authorize]
        public IActionResult Edit(int id)
        {
            if (!this.URLExists(id))
            {
                return this.BadRequest();
            }

            if (!this.UserIsCreator(id, this.User.UserId()))
            {
                return this.Unauthorized();
            }

            URLAddress? url = this.GetURLAddressById(id);
            if (url is null)
            {
                return this.NotFound();
            }

            string theOriginalShortCode = url.ShortUrl.Substring(url.ShortUrl.LastIndexOf('/') + 1);

            URLAddressFormModel urlFormModel = new URLAddressFormModel()
            {
                URL = url.OriginalUrl,
                ShortCode = theOriginalShortCode
            };

            return this.View(urlFormModel);
        }

        [HttpPost]
        [Authorize]
        public IActionResult Edit(int id, URLAddressFormModel model)
        {
            if (!this.URLExists(id))
            {
                return this.BadRequest();
            }

            if (!this.UserIsCreator(id, this.User.UserId()))
            {
                return this.Unauthorized();
            }

            if (!this.ModelState.IsValid)
            {
                return this.View(model);
            }

            URLAddress? url = this.GetURLAddressById(id);
            if (url is null)
            {
                return this.NotFound();
            }

            url.OriginalUrl = model.URL;
            url.ShortUrl = url.ShortUrl.Substring(0, url.ShortUrl.LastIndexOf('/') + 1) + model.ShortCode;

            this.context.SaveChanges();

            return this.RedirectToAction("Index", "Home");
        }

        [Authorize]
        public IActionResult Delete(int id)
        {
            if (!this.URLExists(id))
            {
                return this.BadRequest();
            }

            if (!this.UserIsCreator(id, this.User.UserId()))
            {
                return this.Unauthorized();
            }

            URLAddress? urlData = this.GetURLAddressById(id);
            if (urlData == null)
            {
                return this.BadRequest();
            }

            URLAddressViewModel model = new URLAddressViewModel()
            {
                Id = urlData.Id,
                OriginalUrl = urlData.OriginalUrl,
                ShortUrl = urlData.ShortUrl,
                DateCreated = urlData.DateCreated,
                Visits = urlData.Visits
            };

            return this.View(model);
        }

        [HttpPost]
        [Authorize]
        public IActionResult Delete(URLAddressViewModel model)
        {
            if (!this.URLExists(model.Id))
            {
                return this.BadRequest();
            }

            if (!this.UserIsCreator(model.Id, this.User.UserId()))
            {
                return this.Unauthorized();
            }

            URLAddress? urlAddress = this.GetURLAddressById(model.Id);
            if (urlAddress is null)
            {
                return this.NotFound();
            }

            this.context.URLAddresses.Remove(urlAddress);
            this.context.SaveChanges();

            return this.RedirectToAction("Index", "Home");
        }

        public bool URLExists(int id)
        {
            return this.context.URLAddresses.Any(h => h.Id == id);
        }

        public bool UserIsCreator(int urlId, string userId)
        {
            URLAddress? urlAddress = this.context.URLAddresses.FirstOrDefault(a => a.Id == urlId);
            if (urlAddress is null)
            {
                return false;
            }

            return urlAddress.UserId == userId;
        }

        public URLAddress? GetURLAddressById(int id)
        {
            URLAddress? address = this.context.URLAddresses.Find(id);
            if (address is null)
            {
                return null;
            }

            return address;
        }

        [HttpGet("URLAddressController/RedirectTo/{path:required}", Name = "ShortUrls_RedirectTo")]
        public IActionResult RedirectTo(string path)
        {
            if (path is null)
            {
                return this.NotFound();
            }

            string normalizeUrl = path.Replace("%2F", "/");

            URLAddress urlOriginalAddres = this.context.URLAddresses
                .FirstOrDefault(a => a.ShortUrl == normalizeUrl)!;
            if (urlOriginalAddres.OriginalUrl is null)
            {
                return this.NotFound();
            }

            urlOriginalAddres.Visits++;
            this.context.SaveChanges();

            return this.Redirect(urlOriginalAddres.OriginalUrl);
        }
    }
}

Regular Exam - 18-Feb-2024/Task-2/URLShortener/Views/Home/Index.cshtml
@model IndexViewModel

@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h3 id="headerText">URL Shortener</h3>
    <div class="infoContainer">
        <div class="container" id="ulContainer">
            <ul class="ulIndex">
                <li>
                    Short URLs: <b>@Model.TotalShortURLsCount</b>
                </li>
                <li>
                    URL visitors: <b>@Model.TotalURLVisitorsCount</b>
                </li>
            </ul>
        </div>
        @if (this.User.Identity.IsAuthenticated)
        {
            <div class="container" id="ulContainer">
                <ul class="ulIndex">
                    <li>
                        My URLs: <b>@Model.MyShortURLsCount</b>
                    </li>
                    <li>
                        My visitors: <b>@Model.MyTotalURLVisitorsCount</b>
                    </li>
                </ul>
            </div>
        }
    </div>

    <div class="text-center">
        @if (!this.User.Identity.IsAuthenticated)
        {
            <h3 id="headerText">Latest Created URLs</h3>
        }
        else
        {
            <h3 id="headerText">My URLs</h3>
        }
        @if (!Model.URLAddresses.Any())
        {
            <h3 class="text-center">You don't have any short URLs yet!</h3>
        }
        else
        {
            <table class="urls">
                <thead>
                    <tr>
                        <th>Original URL</th>
                        <th>Short URL</th>
                        <th>Date Created</th>
                        <th>Visits</th>
                        @if (this.User.Identity.IsAuthenticated)
                        {
                            <th>Actions</th>
                        }
                    </tr>
                </thead>
                <tbody>
                    @foreach (var url in Model.URLAddresses)
                    {
                        <tr id="@url.OriginalUrl">
                            <td>
                                <a href="@url.OriginalUrl" target="_blank">@url.OriginalUrl</a>
                            </td>
                            <td>
                                <a class="shorturl" method="get" asp-controller="URLAddress" asp-action="RedirectTo" asp-route-path="@url.ShortUrl">@url.ShortUrl</a>
                            </td>
                            <td>@url.DateCreated.ToString("yyyy/MM/dd HH:mm:ss")</td>
                            <td>@url.Visits</td>
                            @if (this.User.Identity.IsAuthenticated)
                            {
                                <td>
                                    <a asp-controller="URLAddress" asp-action="Edit" asp-route-id="@url.Id" class="btn btn-secondary mb-2" id="editBtn">Edit</a>
                                    <a asp-controller="URLAddress" asp-action="Delete" asp-route-id="@url.Id" class="btn btn-secondary mb-2" id="deleteBtn">Delete</a>
                                </td>
                            }
                        </tr>
                    }
                </tbody>
            </table>
        }
        @if (Model.MyShortURLsCount > 3)
        {
            <div class="paginationContainer">
                @if (this.User.Identity.IsAuthenticated)
                {
                    var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
                    var nextDisabled = !Model.HasNextPage ? "disabled" : "";

                    <span class="pagination">
                        <a asp-action="Index"
                   asp-route-pageNumber="@(Model.PageIndex - 1)"
                   class="btn btn-default @prevDisabled" id="btn">
                            Previous
                        </a>
                    </span>

                    <span class="pagination">
                        <a asp-action="Index"
                   asp-route-pageNumber="@(Model.PageIndex + 1)"
                   class="btn btn-default @nextDisabled" id="btn">
                            Next
                        </a>
                    </span>
                }
            </div>
        }
    </div>
</div>